### ISSUE TITLE
Specifying multiple label selectors is not working correctly

### ISSUE THREAD

**Issue by sanjams-amzn** [aws/sagemaker-hyperpod-recipes#27]
## Describe the bug
When a user supplies multiple values for required or preferred label selectors only, one will get applied instead of all of them

## How to Reproduce?
Define a config like so:
```
...
    label_selector:
      required:
        sagemaker.amazonaws.com/node-health-status:
          - Schedulable
        beta.kubernetes.io/instance-type:
          - ml.p4d.24xlarge
...
```

## Expected behavior
The expected behavior would be that both labels above are applied in the required section.

## Screenshots, error messages or logs
Portion of the pod spec for a pod launched by the above config:
```
    "spec": {
        "affinity": {
            "nodeAffinity": {
                "preferredDuringSchedulingIgnoredDuringExecution": [
                    {
                        "preference": {
                            "matchExpressions": [
                                {
                                    "key": "sagemaker.amazonaws.com/deep-health-check-status",
                                    "operator": "In",
                                    "values": [
                                        "Passed"
                                    ]
                                }
                            ]
                        },
                        "weight": 100
                    }
                ],
                "requiredDuringSchedulingIgnoredDuringExecution": {
                    "nodeSelectorTerms": [
                        {
                            "matchExpressions": [
                                {
                                    "key": "sagemaker.amazonaws.com/node-health-status",
                                    "operator": "In",
                                    "values": [
                                        "Schedulable"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },
```

The bug seems to be that [this line](https://github.com/aws/sagemaker-hyperpod-recipes/blob/45a4c13c3519516aa4c135a89ad9bcc4741bc5e9/launcher/nemo/k8s_templates/training/training.yaml#L107) and the one above it should be flipped. Same goes for the preferred section. 

## Additional context
Here is a portion of the rendered helm chart that was found locally with a config containing multiple `requiredDuringSchedulingIgnoredDuringExecution` keys which seems to be the bug:

```
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: "beta.kubernetes.io/instance-type"
                      operator: In
                      values:
                        - "ml.p4d.24xlarge"
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: "sagemaker.amazonaws.com/node-health-status"
                      operator: In
                      values:
                        - "Schedulable"
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: "sagemaker.amazonaws.com/deep-health-check-status"
                        operator: In
                        values:
                          - "Passed"
```
